SELECT TOP (1000) [intAutoId]
      ,[intAccountId]
      ,[intBusinessUnitId]
      ,[intActivityType]
      ,[strCommnets]
      ,[dteLogTime]
      ,[dteEndTime]
      ,[strUrl]
      ,[isActive]
      ,[dteServerDateTime]
      ,[dteLastActionDateTime]
      ,[intActionBy]
  FROM [APON].[rtm].[tblRTMUserActivityLog]
